### ISSUE TITLE
Send question to other people with answering-functionality

### ISSUE THREAD

**Issue by ronidee** [ronidee/Entscheide-dich#7]
Generate a custom URL (maybe something like: www.example.net/#U_ID=123456) 
Server shows the question and two answers. The will be visible for everybody with this link

**Comment by cuechan** [comment]
This will need some design changes;
Every question needs a unique Id which stays in sync with the server.
The best way is probably to fetch the Questions at the first app start from the server instead of packing them in the .apk itself.

An other way would be to send the whole question to the server... This would make things a bit easier
